const data = {
    products:[
        {
           _id:'1',
           name:'Nike Slim Shirt',
           category:'Shirts',
           image:'images/p1.jpg',
           price:100,
           brand:'Nike',
           rating:5,
           numReviews:10,
           description:'high quality product', 
        },
        {
            _id:'2',
            name:'Nike Fit Shirt',
            category:'Shirts',
            image:'images/p2.jpg',
            price:130,
            brand:'Nike',
            rating:4.5,
            numReviews:12,
            description:'high quality product', 
         },
         {
            _id:'3',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'images/p3.jpg',
            price:200,
            brand:'Nike',
            rating:4,
            numReviews:5,
            description:'high quality product', 
         },
         {
            _id:'4',
            name:'Nike Slim pent',
            category:'pents',
            image:'images/p4.jpg',
            price:150,
            brand:'Nike',
            rating:4.5,
            numReviews:20,
            description:'high quality product', 
         },
         {
            _id:'5',
            name:'Nike Fit pent',
            category:'pents',
            image:'images/p5.jpg',
            price:80,
            brand:'Nike',
            rating:5,
            numReviews:12,
            description:'high quality product', 
         },
         {
            _id:'6',
            name:'Nike Slim pent',
            category:'pents',
            image:'images/p6.jpg',
            price:150,
            brand:'Nike',
            rating:4.8,
            numReviews:8,
            description:'high quality product', 
         }
    ],
};
export default data;